name: Security audit

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

permissions:
  contents: read

jobs:
  security_audit:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
