---
name: Rust compile & test

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
      - name: Run tests (Native)
        run: cargo nextest run --release
      - name: Upload test results
        uses: softprops/action-gh-release@v1
        with:
          files: target/nextest/default/junit.xml
