name: Rust compile & test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
        targets: wasm32-unknown-unknown
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - uses: taiki-e/install-action@nextest
    - uses: Swatinem/rust-cache@v2
    - run: cargo check --tests --benches
    - run: cargo build --verbose
    - run: cargo clippy -- -D warnings
    - name: Run tests (Native)
      run: cargo nextest run --verbose --release
    - name: Run tests (WASM)
      run: wasm-pack test --release --headless --chrome
